### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by emrifan6** [codenomdev/codeigniter4-midtrans#21]
Mohon bantuanya, gagal install lewat composer

 
PS C:\xampp\htdocs\taber> composer require codenom/midtrans
Using version dev-master for codenom/midtrans
./composer.json has been updated
Running composer update codenom/midtrans
Loading composer repositories with package information
Updating dependencies

  Problem 1
    - Root composer.json requires codenom/midtrans dev-master -> satisfiable by codenom/midtrans[dev-master].
    - codenom/midtrans dev-master requires laminas/laminas-json dev-master -> found laminas/laminas-json[2.0.0, ..., 2.6.1, 3.0.0, ..., 3.3.x-dev] but it does not match the constraint.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
PS C:\xampp\htdocs\taber> composer require codenom/midtrans
Using version dev-master for codenom/midtrans
./composer.json has been updated
Running composer update codenom/midtrans
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires codenom/midtrans dev-master -> satisfiable by codenom/midtrans[dev-master].
    - codenom/midtrans dev-master requires laminas/laminas-json dev-master -> found laminas/laminas-json[2.0.0, ..., 2.6.1, 3.0.0, ..., 3.3.x-dev] but it does not match the constraint.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by codenomdev** [comment]
Hi, @emrifan6 

Masalah tersebut sudah diperbaiki.

Terima kasih
