### ISSUE TITLE
PHP 8.0 support?

### ISSUE THREAD

**Issue by mjamilasfihani** [codenomdev/codeigniter4-midtrans#22]
Halo gan? sepertinya php 8.0 udah mulai di support di CodeIgniter4, apakah akan ada update terbaru :)

**Comment by codenomdev** [comment]
Halo @mjamilasfihani 

Akan selalu diperbarui jika ditemukan error.

Jika menemukan kendala, silakan buka Issue pada repositori ini ya.

Terima kasih

**Comment by mjamilasfihani** [comment]
Kendalanya composer.json belum support php 8.0 terimakasih

**Comment by codenomdev** [comment]
Hi, @mjamilasfihani .

Kendala yang dialami sudah kami perbaiki agar mendukung PHP 8.0.

Bisa dilihat perubahannya:

https://github.com/codenomdev/codeigniter4-midtrans/blob/e31cb62ac4ac7d5244955ba8a2471ed6dd9aaa20/composer.json#L24

Akan tetapi, kami tidak bisa meyakinkan bahwa Module ini bisa berjalan sepenuhnya di PHP 8.0.
Jika menemukan masalah, jangan sungkan untuk membuat Issue pada repositori ini.

Terima kasih

**Comment by mjamilasfihani** [comment]
Terimakasih, saya akan membuat issue baru jika ada kendala
